### ISSUE TITLE
MODS datastream not available for transform function

### ISSUE THREAD

**Issue by bondjimbond** [ulsdevteam/islandora_datastreams_io#13]
As recommended in a [Google Group discussion](https://groups.google.com/d/topic/islandora/YE63TNDkO4U/discussion) by @bgilling, I'm trying to use this module to apply a self-transform to many objects, using the "Transform Datastreams" option.

But I'm hitting a wall -- the MODS datastream is not available to be transformed.

The select list only offers the following datastream choices:

- DC
- COLLECTION_POLICY
- AUDIT
- PRESERVATION (a custom datastream)

I'm guessing that MODS is somehow getting dropped somewhere in these lines? https://github.com/ulsdevteam/islandora_datastreams_io/blob/master/includes/transform.form.inc#L26-L36

**Comment by bondjimbond** [comment]
It seems the problem is happening in this line: `$datastreams = islandora_datastreams_io_textxml_datastreams($all_datastreams)`

This is where the complete list of datastreams is stripped down, and MODS is excluded. I added `dd($all_datastreams)` and `dd($datastreams)` after that line to find this.

There's something wrong with the query in [that function in includes/utilities.inc](https://github.com/ulsdevteam/islandora_datastreams_io/blob/533322af95aac62eb0845b848224bac11eb5c338/includes/utilities.inc#L175). The resulting "numFound" for MODS is zero, when it definitely shouldn't be.

Query: https://github.com/ulsdevteam/islandora_datastreams_io/blob/533322af95aac62eb0845b848224bac11eb5c338/includes/utilities.inc#L196

**Comment by wgilling** [comment]
Thanks for the detailed report.  I suspect that the mimetype for MODS datastreams in your system is not text/xml -- and that they are all "application/xml".  I confirmed this by faceting all of the records in our solr index by the field fedora_datastream_latest_MODS_MIMETYPE_ms -- and we have both text/xml and application/xml.

There is nothing other than that wrong with that query.  I will patch the code pretty quickly to also let this other mimetype through as possible datastreams for xslt transform operations.  Stay tuned ... this shouldn't take very long.

**Comment by bondjimbond** [comment]
Thanks, @bgilling. I believe application/xml is the "correct" mimetype for XML, but text/xml has a tendency of popping up all over the place as well, so it's definitely best to account for both.

**Comment by wgilling** [comment]
could you please pull the latest code in the "master" branch and try the transform page again??  The code should now display your MODS and allow this to go to the next step in processing XSL for you.

**Comment by bondjimbond** [comment]
Huzzah, it works! And my transform works, too. Thanks!

**Comment by bondjimbond** [comment]
@bgilling One more thought... Would it be plausible to allow for local transforms as well as a file upload? i.e. if you want to apply the transforms located in Islandora XML Forms, which are already in the system -- you could use hook_xml_form_builder_get_self_transforms() to generate the list and select one.
