### ISSUE TITLE
Respect namespace restrictions

### ISSUE THREAD

**Issue by bondjimbond** [ulsdevteam/islandora_datastreams_io#3]
The module currently does not respect the Islandora site's configured namespace restrictions for datastream import or export. This means that on a site where certain namespaces are meant to be inaccessible, objects with those namespaces can still be exported and have datastreams pushed on them.

This is particularly important in a multisite environment, where several child sites share a single Fedora repository, and namespace restrictions keep them out of each other's territory.

This should be fairly easily remedied using `islandora_namespace_accessible()` when building the list of PIDs for export, and when reading the list of PIDs for import.

**Comment by wgilling** [comment]
I am not sure that I understand your point.  If any islandora site in a multi-site is using namespace restrictions, using this tool to import any object that has a namespace that is relevant to a different site could be exposed on the wrong site -- wouldn't that be controlled by the sites' individual namespace restrictions?

**Comment by bondjimbond** [comment]
> wouldn't that be controlled by the sites' individual namespace restrictions?

That's the problem -- this tool ignores those restrictions.

Let's say my site, site1.islandorasite.net, is only allowed to use the namespaces "ns0" and "ns1". Meanwhile, it shares a Fedora repository with site2.islandorasite.net, using the namespaces "ns2" and "ns3".

So, I need to batch edit a bunch of objects with the Citation CModel, across multiple collections. So, I select "model" and choose the Citation CModel.

Click Export, now I have all the Citation objects from all the namespaces, including ones that should be invisible to me.

I'm a bit careless, and I do a batch find/replace across all the files in that export, and do an import.

Because namespace restrictions are ignored through this module's operations, I have now edited objecst in the ns2 and ns3 namespaces -- objects in someone else's sites.

**Comment by bondjimbond** [comment]
I'll add that I tested this before posting the issue, as I run a multisite and namespace restrictions are often an issue for us. In a fresh Vagrant machine, I enabled restrictions and blocked access to a particular namespace. This module did export objects from the restricted namespace, and allowed me to push datastreams to those restricted namespaces.

**Comment by wgilling** [comment]
Good points.  We do not implement namespace restrictions at all like this across our sites, but instead use isMemberOfSite RELS-EXT relationship for objects.

I will add this function call to both sides of datastream import / export.

**Comment by bondjimbond** [comment]
Thanks! You may also need to add this line in order to call on the function:
`module_load_include('inc', 'islandora', 'includes/utilities');`

**Comment by wgilling** [comment]
The code has been changed to address this (as well as the hidden and __MACOSX import issue) in the latest commit -- 73f4fa5b589ae1f204b5a7fb0d3fdeb5d47ea63b.  Please let me know if there is anything else.

**Comment by bondjimbond** [comment]
Tested... 

Namespace restriction works for import! If the file contains a restricted namespace, it ignores it, and only recognizes the allowed files.

For export, though, the files generated are no good. See #4

**Comment by wgilling** [comment]
Happy to help.  Thanks for the recommendations.
