### ISSUE TITLE
Export stops working after last commits

### ISSUE THREAD

**Issue by bondjimbond** [ulsdevteam/islandora_datastreams_io#4]
Now when you set up an export, it generates a ZIP file of zero bytes. If you unzip that file, you start a chain..

file.zip -> file.zip.cpgz -> file 2.zip -> file 2.zip.cpgz etc.

Since two commits were added at once, I'm not sure which is the culprit.

**Comment by bondjimbond** [comment]
You also get the following warnings/notices:

> Notice: Undefined variable: inspect_pidssudo in islandora_datastreams_io_pids_namespace_accessible() (line 271 of /var/www/drupal/sites/all/modules/islandora_datastreams_io/includes/utilities.inc).
> Warning: Invalid argument supplied for foreach() in islandora_datastreams_io_pids_namespace_accessible() (line 271 of /var/www/drupal/sites/all/modules/islandora_datastreams_io/includes/utilities.inc).
> Warning: filesize(): stat failed for /tmp/datastream_io_datastreams_144405_020105/file.zip in islandora_datastreams_io_export_form_submit() (line 223 of /var/www/drupal/sites/all/modules/islandora_datastreams_io/includes/export.form.inc).

**Comment by wgilling** [comment]
Oh no --- I can see the word "sudo " in there.  I typed in the wrong console and didn't notice that I changed the code.  The updated code I have tested to export non 0-byte zip files is being committed now.

**Comment by bondjimbond** [comment]
Cool! Glad it's such a simple error to fix. If you let me know when you push that commit I'll test some more.

**Comment by wgilling** [comment]
The change has just been pushed f7f22e6a34d0de08607a79767cfe811df5c4b195.  I will keep this issue opened until you've had a chance to test.

**Comment by bondjimbond** [comment]
Yep, the export problem is fixed. Still have import problems, though... will reply on other ticket.
